{"uuid": "648f0042-4b1e-4cb1-89c2-e85cb7b4b3b1", "children": ["0cf1c92f-acbe-49b1-838b-dcab1f11c894"], "befores": [{"name": "setup_Login_uno", "status": "passed", "attachments": [{"name": "login_scr_ant", "source": "56828ab7-2742-496d-998a-b4fb33d255e4-attachment.png", "type": "image/png"}, {"name": "login_scr_desp", "source": "96d7f7c5-49b4-40cf-8e46-77c07585ea71-attachment.png", "type": "image/png"}], "start": 1685128152626, "stop": 1685128165126}], "afters": [{"name": "setup_Login_uno::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00418893+48451]\n\t(No symbol) [0x003AB8A1]\n\t(No symbol) [0x002B4F20]\n\t(No symbol) [0x002D7A42]\n\t(No symbol) [0x002D8F2D]\n\tGetHandleVerifier [0x00678E3A+2540266]\n\tGetHandleVerifier [0x006B8959+2801161]\n\tGetHandleVerifier [0x006B295C+2776588]\n\tGetHandleVerifier [0x004A2280+612144]\n\t(No symbol) [0x003B4F6C]\n\t(No symbol) [0x003B11D8]\n\t(No symbol) [0x003B12BB]\n\t(No symbol) [0x003A4857]\n\tBaseThreadInitThunk [0x75826359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77CF87D4+228]\n\tRtlGetAppContainerNamedObjectPath [0x77CF87A4+180]\n\n", "trace": "  File \"C:\\Users\\alexf\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\alexf\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\alexf\\Desktop\\Automatizaci√≥n Selenium Python\\Ejercicios\\Ejercicios_Modulo_10_Pytest_Reportes\\Ejercicios_Pytest_Reportes\\Test1_Fixture_Decorate_2.py\", line 48, in setup_Login_uno\n    driver.close()\n  File \"C:\\Users\\alexf\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\alexf\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\alexf\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1685128207568, "stop": 1685128207803}], "start": 1685128152626, "stop": 1685128207803}